### ISSUE TITLE
I get some a error in compling!

### ISSUE THREAD

**Issue by tomjeans** [FeiGeChuanShu/ncnn_Android_PP-TinyPose#2]
C:\Users\Administrator\Desktop\ncnn_tinypose\ncnn_Android_PP-TinyPose-main\app\src\main\jni\nanodet.cpp:31:14: error: call to member function 'create' is ambiguous
How to solve the problem? Thanks!

**Comment by FeiGeChuanShu** [comment]
> C:\Users\Administrator\Desktop\ncnn_tinypose\ncnn_Android_PP-TinyPose-main\app\src\main\jni\nanodet.cpp:31:14: error: call to member function 'create' is ambiguous How to solve the problem? Thanks!

which version of ncnn you use, you can try ncnn-20211122-android-vulkan first

**Comment by tomjeans** [comment]
Thanks! I have solved this error.
